title: diverwil1995 的部落格
description: 這裡除了技術文章，也會分享一些生活點滴。
author: Wilson 小鬼

# 分頁設置
paginate: 10
paginate_path: "/page:num/"

# 集合設置
collections:
  lists:
    output: true

# 默認布局設置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"